# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-08 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0002_snippet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
